// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB'] ?? '',
    appId: '1:54963688270:web:55126e12272b2b4979041f',
    messagingSenderId: '54963688270',
    projectId: 'testproject-805e7',
    authDomain: 'testproject-805e7.firebaseapp.com',
    storageBucket: 'testproject-805e7.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID'] ?? '',
    appId: '1:54963688270:android:1ed4f466fec83ca579041f',
    messagingSenderId: '54963688270',
    projectId: 'testproject-805e7',
    storageBucket: 'testproject-805e7.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS'] ?? '',
    appId: '1:54963688270:ios:d2ea732813e3ecb079041f',
    messagingSenderId: '54963688270',
    projectId: 'testproject-805e7',
    storageBucket: 'testproject-805e7.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MAC'] ?? '',
    appId: '1:54963688270:ios:d2ea732813e3ecb079041f',
    messagingSenderId: '54963688270',
    projectId: 'testproject-805e7',
    storageBucket: 'testproject-805e7.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX5z3S0z8qPMqg-dXP5Cak085AWF4MHEs',
    appId: '1:54963688270:web:bc69b327c655e3cf79041f',
    messagingSenderId: '54963688270',
    projectId: 'testproject-805e7',
    authDomain: 'testproject-805e7.firebaseapp.com',
    storageBucket: 'testproject-805e7.firebasestorage.app',
  );
}
